name: 'Get & Cache dependencies'
# action is not workflow -> don't have 'on' keyword
description: 'Get the dependencies (via npm) and cache them'
runs: 
  using: 'composite' # this is composite action
  steps: 
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash # new